apiVersion: v1
kind: Service
metadata:
  name: recipelist-cluster-ip
spec:
  type: ClusterIP
  # ServerClusterIp is coupled to the selector (metadata) tags.
  # Which are entirely customizable.
  selector:
    folder: recipelist-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
